on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:

    - name: Show dir
      run: ls -la /home/runner/work/jenkins-test/jenkins-test
    
    - name: Show PATH
      run: pwd

    - name: My script
      run: ././my_script.sh
