on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
    
    - name: My script
      run: bash pwd
      run: bash jenkins-test/my_script.sh
