on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3    

    - name: My script
      run: |
        chmod a+x ./my_script.sh
        ./my_script.sh
