on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jenkins-test 

    steps:
    
    - name: My script
      run: ./my_script.sh
